# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078be950d0d7088e30c11fe4d3f43abfa17869aca268bb8e2e52ea31dbea4415ccacead1afa63407588e4f6b7c6cbc68327accf99e9d8bf8505ac2905899e8f9

test:
  secret_key_base: 5cfebb76a947bc0d314c0155e79b93f339a07dff97f2627038f12931d81c86a2b53a08785cdb730ecdaf7589a7f99a26c1f8d67d43ff7c5457d0c18148d43203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
